[package]
name = "ashpd-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ashpd = { version = "0.3.2", features = ["log"] }
tracing = "0.1"
tracing-subscriber = "0.3"
async-std = "1.10.0"
